version: 2

models:
  - name: SalesOrderItems_Total
    description: "Group on product ID to get the total amounts and quantites."
    columns:
      - name: PRODUCTID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: SalesOrderItems_TotalWeight
    description: "Join SalesOrderItems_Total with Products to get the total weight of the sold orders."
    columns:
      - name: PRODUCTID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

sources:
  - name: dbt_showcase
    tables:
      - name: products_bronze
      - name: salesorderitems_bronze